version: 0.2

env:
  variables:
    TEST_VAR: "t2.micro"

phases:
  install:
    commands:
      - set -e
      - echo Entered the install phase
      - apt-get update -y
    finally:
      - echo This always runs even if the update or install command fails

  pre_build:
    commands:
      - set -e
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails

  build:
    commands:
      - set -e
      - ls -altr
      - printenv
      - echo $TEST_VAR
      - echo $AWS_REGION
      - echo $CODEBUILD_BUILD_NUMBER
      - echo Entered the build phase...
      - echo Build started on `date`
      - aws s3 ls
      - cat newfile.txt
      - bash pawan.sh
    finally:
      - echo This always runs even if the install command fails

  post_build:
    commands:
      - set -e
      - echo Entered the post_build phase...
      - echo Build completed on `date`
